<?php

namespace Nva\FontBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DemoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Nva\FontBundle\Controller\DemoController();
        return $instance;
    }
}
