parameters:
#    nva_font.example.class: Nva\FontBundle\Example

services:
#    nva_font.example:
#        class: %nva_font.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
